default: &default
  adapter: sqlite3
  database: <%= ENV.fetch('DB_NAME') %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default

test:
  <<: *default
  database: <%= "test_#{ENV.fetch('DB_NAME')}" %>

production:
  <<: *default
